In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [ ]:
documents = [
    "This is a list which containig sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings."
]


In [ ]:
query = "keyword-based search"

In [ ]:
import re
def preprocess_text(text):
    # Remove punctuation and convert to lowercase
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    return text

In [ ]:
preprocess_document = [preprocess_text(doc) for doc in documents]

In [ ]:
preprocess_document

['this is a list which containig sample documents',
 'keywords are important for keywordbased search',
 'document analysis involves extracting keywords',
 'keywordbased search relies on sparse embeddings']

In [ ]:
print("Preprocessed Query")
print(query)

Preprocessed Query
keyword-based search


In [ ]:
preprocessed_query = preprocess_text(query)
preprocessed_query

'keywordbased search'

In [ ]:
vector = TfidfVectorizer()

In [ ]:
x = vector.fit_transform(preprocess_document)

In [ ]:
x.toarray()

array([[0.        , 0.        , 0.37796447, 0.        , 0.37796447,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
        0.        , 0.37796447, 0.        , 0.        , 0.37796447,
        0.37796447],
       [0.        , 0.4533864 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4533864 , 0.4533864 , 0.        ,
        0.        , 0.35745504, 0.35745504, 0.        , 0.        ,
        0.        , 0.        , 0.35745504, 0.        , 0.        ,
        0.        ],
       [0.46516193, 0.        , 0.        , 0.46516193, 0.        ,
        0.        , 0.46516193, 0.        , 0.        , 0.46516193,
        0.        , 0.        , 0.36673901, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.43671931, 0.        , 0.        , 0.       

In [ ]:
x.toarray()[0]

array([0.        , 0.        , 0.37796447, 0.        , 0.37796447,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
       0.        , 0.37796447, 0.        , 0.        , 0.37796447,
       0.37796447])

In [ ]:
query_embedding = vector.transform([preprocessed_query])

In [ ]:
query_embedding.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        ]])

In [ ]:
similarities = cosine_similarity(x, query_embedding)
similarities

array([[0.        ],
       [0.50551777],
       [0.        ],
       [0.48693426]])

In [ ]:
np.argsort(similarities,axis = 0)

array([[0],
       [2],
       [3],
       [1]])

In [ ]:
#Ranking
rancked_indeces = np.argsort(similarities,axis = 0)[::-1].flatten()

In [ ]:
rancked_indeces

array([1, 3, 2, 0])

In [ ]:
rancked_doc = [documents[i] for i in rancked_indeces]

In [ ]:
rancked_doc

['Keywords are important for keyword-based search.',
 'Keyword-based search relies on sparse embeddings.',
 'Document analysis involves extracting keywords.',
 'This is a list which containig sample documents.']

In [ ]:
for i,doc in enumerate(rancked_doc):
    print(f"Rank {i+1}. {doc}")

Rank 1. Keywords are important for keyword-based search.
Rank 2. Keyword-based search relies on sparse embeddings.
Rank 3. Document analysis involves extracting keywords.
Rank 4. This is a list which containig sample documents.


In [ ]:
query

'keyword-based search'

In [ ]:
document_embeddings = np.array([
    [0.634, 0.234, 0.867, 0.042, 0.249],
    [0.123, 0.456, 0.789, 0.321, 0.654],
    [0.987, 0.654, 0.321, 0.123, 0.456]
])


In [ ]:
# Sample search query (represented as a dense vector)
query_embedding = np.array([[0.789, 0.321, 0.654, 0.987, 0.123]])

In [ ]:
# Calculate cosine similarity between query and documents
similarity = cosine_similarity(document_embeddings, query_embedding)

In [ ]:
similarity

array([[0.73558979],
       [0.67357898],
       [0.71517305]])

In [ ]:
rancked_index = np.argsort(similarity,axis = 0)[::-1].flatten()

In [ ]:
rancked_index

array([0, 2, 1])

In [ ]:
# Output the rancked documents
for i, idx in enumerate(rancked_index):
    print(f"Rank {i+1}: document_embeddings{[idx+1]}")

Rank 1: document_embeddings[1]
Rank 2: document_embeddings[3]
Rank 3: document_embeddings[2]


In [ ]:
doc_path = "/content/Retrieval Augumented Generation Paper.pdf"

In [ ]:
!pip install pypdf

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 290.4/290.4 kB 6.0 MB/s eta 0:00:00


In [ ]:
!pip install langchain_community

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 974.6/974.6 kB 18.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 321.8/321.8 kB 16.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.1/127.1 kB 20.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 7.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.0/145.0 kB 21.0 MB/s eta 0:00:00


In [ ]:
from langchain_community.document_loaders import PyPDFLoader

In [ ]:
loader = PyPDFLoader(doc_path)

In [ ]:
docs = loader.load()

In [ ]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

In [ ]:
splitter = RecursiveCharacterTextSplitter(chunk_size = 200, chunk_overlap = 30)

In [ ]:
chunks = splitter.split_documents(docs)

In [ ]:
#chunks

In [ ]:
from langchain.embeddings import HuggingFaceInferenceAPIEmbeddings

In [ ]:
HF_TOKEN = "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"

In [ ]:
embeddings = HuggingFaceInferenceAPIEmbeddings(api_key = HF_TOKEN, model_name = "BAAI/bge-base-en-v1.5")

In [ ]:
!pip install chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.5/559.5 kB 7.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 16.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 15.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 10.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 6.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 37.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 kB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.0/107.0 kB 19.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 12.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.7/283.7 kB 39.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 M

In [ ]:
from langchain.vectorstores import Chroma

In [ ]:
vector_store = Chroma.from_documents(chunks, embeddings)

In [ ]:
vectorstore_retriever = vector_store.as_retriever(search_kwargs = {"k":3})

In [ ]:
vectorstore_retriever

VectorStoreRetriever(tags=['Chroma', 'HuggingFaceInferenceAPIEmbeddings'], vectorstore=<langchain_community.vectorstores.chroma.Chroma object at 0x790b3e441480>, search_kwargs={'k': 3})

In [ ]:
!pip install rank_bm25 # updated version of TF-IDF

In [ ]:
from langchain.retrievers import BM25Retriever, EnsembleRetriever

In [ ]:
keyword_retriever = BM25Retriever.from_documents(chunks)

In [ ]:
keyword_retriever.k = 3

In [ ]:
ensemble_retriever = EnsembleRetriever(retrievers = [vectorstore_retriever, keyword_retriever], weights = [0.3,0.7])

In [ ]:
model_name = "HuggingFaceH4/zephyr-7b-beta"

In [ ]:
!pip install bitsandbytes

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 MB 8.2 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-m

In [ ]:
!pip install accelerate

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.4/309.4 kB 6.1 MB/s eta 0:00:00


In [ ]:
import torch
from transformers import (AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline)
from langchain import HuggingFacePipeline

In [ ]:
def load_quantized_model(model_name:str):
  """
  model_name : Name or path of the model to be loaded
  return : Quantized model
  """
  bnb_config = BitsAndBytesConfig(
      load_in_4bit=True,
      bnb_4bit_use_double_quant=True,
      bnb_4bit_quant_type="nf4",
      bnb_4bit_compute_dtype=torch.bfloat16
  )

  model = AutoModelForCausalLM.from_pretrained(
      model_name,
      torch_dtype = torch.bfloat16,
      quantization_config=bnb_config,
  )
  return model

In [ ]:
# initializing tokenizer
def initialize_tokenizer(model_name:str):
  """
  model_name : Name or path of the model to be loaded
  return : Initialized Tokenizer
  """
  tokenizer = AutoTokenizer.from_pretrained(model_name, return_token_type_ids = False)
  tokenizer.bos_token_id = 1
  return tokenizer

In [ ]:
tokenizer = initialize_tokenizer(model_name)

tokenizer_config.json:   0%|          | 0.00/1.43k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

In [ ]:
model = load_quantized_model(model_name)

config.json:   0%|          | 0.00/638 [00:00<?, ?B/s]

`low_cpu_mem_usage` was None, now set to True since model is quantized.


model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

model-00001-of-00008.safetensors:   0%|          | 0.00/1.89G [00:00<?, ?B/s]

model-00002-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00003-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00004-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00005-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00006-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00007-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00008-of-00008.safetensors:   0%|          | 0.00/816M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [ ]:
pipeline = pipeline("text-generation",
                    model = model,
                    tokenizer = tokenizer,
                    use_cache = True,
                    device_map = "auto",
                    max_length = 2048,
                    do_sample = True,
                    top_k = 5,
                    num_return_sequences = 1,
                    eos_token_id=tokenizer.eos_token_id,
                    pad_token_id=tokenizer.pad_token_id,
)

In [ ]:
llm = HuggingFacePipeline(pipeline = pipeline)

/usr/local/lib/python3.10/dist-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The class `HuggingFacePipeline` was deprecated in LangChain 0.0.37 and will be removed in 0.3. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFacePipeline`.
  warn_deprecated(


In [ ]:
from langchain.chains import RetrievalQA

In [ ]:
normal_chain = RetrievalQA.from_chain_type(llm = llm, chain_type = "stuff",
                                           retriever = ensemble_retriever)

In [ ]:
hybrid_chain = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff",
                                           retriever=ensemble_retriever)

In [ ]:
response1 = normal_chain.invoke("What is RAG token model?")

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


In [ ]:
response1

{'query': 'What is RAG token model?',
 'result': "Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\nSun Also Rises”. Similarly, document 1 dominates the posterior when “A Farewell to Arms” is\ngenerated. Intriguingly, after the first token of each book is generated, the document posterior flattens.\n\nthe parameters of a language model? arXiv e-prints , 2020. URL https://arxiv.org/abs/\n2002.08910 .\n[53] Stephen Robertson and Hugo Zaragoza. The probabilistic relevance framework: Bm25 and\n\nretriever, and then the generator produces a distribution for the next output token for each document,\n\nRAG-Token The RAG-Token model can be seen as a standard, autoregressive seq2seq genera-\ntor with transition probability: p′\nθ(yi|x,y 1:i−1) =∑\nz∈top-k(p(·|x))pη(zi|x)pθ(yi|x,zi,y1:i−1)To\n\ndistribution over generated text. In one approach, RAG-Sequence , the model uses the same 

In [ ]:
response1.get('result')

"Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\nSun Also Rises”. Similarly, document 1 dominates the posterior when “A Farewell to Arms” is\ngenerated. Intriguingly, after the first token of each book is generated, the document posterior flattens.\n\nthe parameters of a language model? arXiv e-prints , 2020. URL https://arxiv.org/abs/\n2002.08910 .\n[53] Stephen Robertson and Hugo Zaragoza. The probabilistic relevance framework: Bm25 and\n\nretriever, and then the generator produces a distribution for the next output token for each document,\n\nRAG-Token The RAG-Token model can be seen as a standard, autoregressive seq2seq genera-\ntor with transition probability: p′\nθ(yi|x,y 1:i−1) =∑\nz∈top-k(p(·|x))pη(zi|x)pθ(yi|x,zi,y1:i−1)To\n\ndistribution over generated text. In one approach, RAG-Sequence , the model uses the same document\nto predict each target token. The secon

In [ ]:
response2 = hybrid_chain.invoke("What is RAG token model?")

In [ ]:
response2

{'query': 'What is RAG token model?',
 'result': "Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\nSun Also Rises”. Similarly, document 1 dominates the posterior when “A Farewell to Arms” is\ngenerated. Intriguingly, after the first token of each book is generated, the document posterior flattens.\n\nthe parameters of a language model? arXiv e-prints , 2020. URL https://arxiv.org/abs/\n2002.08910 .\n[53] Stephen Robertson and Hugo Zaragoza. The probabilistic relevance framework: Bm25 and\n\nretriever, and then the generator produces a distribution for the next output token for each document,\n\nRAG-Token The RAG-Token model can be seen as a standard, autoregressive seq2seq genera-\ntor with transition probability: p′\nθ(yi|x,y 1:i−1) =∑\nz∈top-k(p(·|x))pη(zi|x)pθ(yi|x,zi,y1:i−1)To\n\ndistribution over generated text. In one approach, RAG-Sequence , the model uses the same 

In [ ]:
print(response2.get('result'))

Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

Sun Also Rises”. Similarly, document 1 dominates the posterior when “A Farewell to Arms” is
generated. Intriguingly, after the first token of each book is generated, the document posterior flattens.

the parameters of a language model? arXiv e-prints , 2020. URL https://arxiv.org/abs/
2002.08910 .
[53] Stephen Robertson and Hugo Zaragoza. The probabilistic relevance framework: Bm25 and

retriever, and then the generator produces a distribution for the next output token for each document,

RAG-Token The RAG-Token model can be seen as a standard, autoregressive seq2seq genera-
tor with transition probability: p′
θ(yi|x,y 1:i−1) =∑
z∈top-k(p(·|x))pη(zi|x)pθ(yi|x,zi,y1:i−1)To

distribution over generated text. In one approach, RAG-Sequence , the model uses the same document
to predict each target token. The second approach, RAG-To